# Generated by Django 5.2.5 on 2025-12-26 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField(choices=[(1, 'System Message'), (10, 'Event Reminder'), (11, 'Event Updated'), (12, 'Event Cancelled'), (13, 'Event Invitation'), (20, 'Match Scheduled'), (21, 'Results Posted'), (22, 'Standings Updated'), (23, 'League Announcement'), (24, 'League Invitation'), (25, 'Session Reminder'), (26, 'Session Cancelled'), (30, 'Membership Expiring'), (31, 'Membership Renewed'), (32, 'Renewal Period Open'), (33, 'Membership Approved'), (34, 'Membership Rejected'), (35, 'Club Announcement'), (40, 'Direct Message'), (41, 'Mentioned in Message'), (50, 'New Follower'), (51, 'Partner Request'), (60, '50 Games Played'), (61, '100 Games Played'), (62, '500 Games Played'), (63, 'Win Streak'), (64, 'Rank Improved'), (70, 'Role Assigned'), (71, 'Role Removed'), (80, 'System Maintenance'), (81, 'System Update')], help_text='Type of notification')),
                ('title', models.CharField(help_text='Short title (e.g., "Event Invitation")', max_length=255)),
                ('message', models.TextField(help_text='Full notification message')),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has read this notification')),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to when clicked (e.g., "/events/101")', max_length=500)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object (e.g., league_id, match_id)', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object (e.g., "league", "match", "club")', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text='User who triggered this notification (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'notification_type', 'is_read'], name='notificatio_recipie_9ee1e3_idx')],
            },
        ),
    ]
