# Generated by Django 5.2.5 on 2025-12-27 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_role_name'),
        ('leagues', '0003_alter_roundrobinpattern_options_and_more'),
        ('matches', '0002_match_generation_format_match_match_day_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_object_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_object_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_label',
            field=models.CharField(blank=True, help_text='Label for action button (e.g., "View Match", "Renew Membership")', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Related club (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AddField(
            model_name='notification',
            name='league',
            field=models.ForeignKey(blank=True, help_text='Related league (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
        migrations.AddField(
            model_name='notification',
            name='match',
            field=models.ForeignKey(blank=True, help_text='Related match (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data (e.g., milestone details, match scores)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='When user read this notification', null=True),
        ),
    ]
