# Generated by Django 5.2.5 on 2026-01-10 22:05

import django.db.models.deletion
import notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_club_banner_url_club_club_type_and_more'),
        ('leagues', '0004_league_allow_waitlist_league_image_url_and_more'),
        ('matches', '0002_match_generation_format_match_match_day_and_more'),
        ('notifications', '0003_notification_image_url_notification_is_pinned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_pinned',
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to when clicked (e.g., "/events/101")', max_length=500)),
                ('action_label', models.CharField(blank=True, help_text='Label for action button (e.g., "View Match", "Renew Membership")', max_length=100)),
                ('is_pinned', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, default=notifications.models.get_default_expiry_date, help_text='Announcement expires after this date (default: 30 days from creation)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(help_text='Club this announcement belongs to (REQUIRED - for permissions and organization)', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='clubs.club')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(blank=True, help_text='Optional: Narrows audience to league participants only', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='leagues.league')),
                ('match', models.ForeignKey(blank=True, help_text='Optional: Narrows audience to match participants only', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='matches.match')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['club', '-created_at'], name='notificatio_club_id_3147b2_idx'), models.Index(fields=['league', '-created_at'], name='notificatio_league__35e5e7_idx'), models.Index(fields=['match', '-created_at'], name='notificatio_match_i_753df1_idx'), models.Index(fields=['is_pinned', '-created_at'], name='notificatio_is_pinn_fa0e70_idx')],
            },
        ),
    ]
