# Generated by Django 5.2.5 on 2026-01-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'System Message'), (10, 'Event Reminder'), (11, 'Event Updated'), (12, 'Event Cancelled'), (13, 'Event Invitation'), (20, 'Match Scheduled'), (21, 'Results Posted'), (22, 'Standings Updated'), (23, 'League Announcement'), (24, 'League Invitation'), (25, 'Session Reminder'), (26, 'Session Cancelled'), (30, 'Membership Expiring'), (31, 'Membership Renewed'), (32, 'Renewal Period Open'), (33, 'Membership Approved'), (34, 'Membership Rejected'), (35, 'Club Announcement'), (36, 'Membership Suspended'), (40, 'Direct Message'), (41, 'Mentioned in Message'), (50, 'New Follower'), (51, 'Partner Request'), (60, '50 Games Played'), (61, '100 Games Played'), (62, '500 Games Played'), (63, 'Win Streak'), (64, 'Rank Improved'), (70, 'Role Assigned'), (71, 'Role Removed'), (80, 'System Maintenance'), (81, 'System Update')], default=35, help_text='Type of announcement'),
            preserve_default=False,
        ),
    ]
