# Generated by Django 5.2.5 on 2026-01-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_rename_message_notification_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_label',
            field=models.CharField(blank=True, default='', help_text='Label for action button (e.g., "View Match", "Renew Membership")', max_length=100),
            preserve_default=False,
        ),
    ]
