# Generated by Django 5.2.5 on 2025-12-01 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0007_remove_clubmembership_level_clubmembership_level'),
        ('leagues', '0001_initial'),
        ('public', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtClubAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation_type', models.CharField(choices=[('priority', 'Priority Access'), ('exclusive', 'Exclusive Access (certain times)'), ('partner', 'Partner Club'), ('shared', 'Shared Access')], default='priority', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='e.g., "Club has priority Mondays 8-12pm" or "Exclusive access for leagues"', null=True)),
                ('start_date', models.DateField(blank=True, help_text='When affiliation starts (e.g., start of season)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When affiliation ends (e.g., end of season)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_affiliations', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Court-Club Affiliation',
            },
        ),
        migrations.CreateModel(
            name='CourtLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Court name (e.g., Parc Optimiste, Tennis 13, Centre Pickle)', max_length=200)),
                ('number_of_courts', models.IntegerField(default=1, help_text='Total number of courts at this location')),
                ('booking_website', models.URLField(blank=True, help_text='Link to external booking site (e.g., www.pickleballenligne.com/PSJ)', null=True)),
                ('description', models.TextField(blank=True, help_text='Additional info about the court (e.g., "Outdoor courts, covered")', null=True)),
                ('photo', models.URLField(blank=True, help_text='Photo of court location', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(help_text='Physical address of court location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_locations', to='public.address')),
                ('affiliated_clubs', models.ManyToManyField(blank=True, help_text='Clubs that have priority access or block bookings at this location', related_name='affiliated_courts', through='courts.CourtClubAffiliation', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Court Location',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='courtclubaffiliation',
            name='court_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_affiliations', to='courts.courtlocation'),
        ),
        migrations.CreateModel(
            name='CourtLocationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.CharField(help_text="e.g., 'Courts blocked for Tennis club'.", max_length=200)),
                ('court_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='courts.courtlocation')),
            ],
        ),
        migrations.CreateModel(
            name='CourtScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for this recurring block')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('block_type', models.CharField(choices=[('league', 'League'), ('competitive', 'Competitive Play'), ('recreative', 'Recreative Play'), ('skill_restricted', 'Skill Restricted (3.5+, 4.0+, etc.)'), ('public', 'Public Open Play'), ('drill', 'Drill/Training'), ('tournament', 'Tournament'), ('blocked', 'Blocked/Reserved'), ('maintenance', 'Maintenance/Closed')], max_length=20)),
                ('title', models.CharField(help_text='e.g., "Groupe Action Pickleball", "Competitive", "PUBLIC", "3.5+"', max_length=100)),
                ('description', models.CharField(blank=True, help_text='e.g., "4 terrains", "Tous les membres", "T5-T6-T7-T8"', max_length=200, null=True)),
                ('courts_affected', models.CharField(blank=True, help_text='Which courts (e.g., "1-4", "5-8", "All", "T5,T6,T7,T8")', max_length=50, null=True)),
                ('background_color', models.CharField(blank=True, help_text='Hex color for schedule display (e.g., #FF00FF for magenta)', max_length=20, null=True)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Text color for readability', max_length=20)),
                ('active_from', models.DateField(blank=True, help_text='When this schedule block starts (e.g., season start)', null=True)),
                ('active_until', models.DateField(blank=True, help_text='When this schedule block ends (e.g., season end)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, help_text='Link to club if this is club-specific', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_schedule_blocks', to='clubs.club')),
                ('court_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='courts.courtlocation')),
                ('created_by', models.ForeignKey(blank=True, help_text='League organizer or admin who created this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_blocks_created', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(blank=True, help_text='Link to league if this is a league block', null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
            options={
                'verbose_name': 'Court Schedule Block',
                'ordering': ['court_location', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserCourtBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_number', models.CharField(blank=True, help_text='Specific court number (if known, e.g., "14", "Court 2", "T5")', max_length=20, null=True)),
                ('booking_date', models.DateField(help_text='Date of booking')),
                ('start_time', models.TimeField(help_text='Start time')),
                ('end_time', models.TimeField(help_text='End time')),
                ('booking_type', models.CharField(choices=[('practice', 'Practice Session'), ('casual', 'Casual Play'), ('lesson', 'Lesson'), ('drill', 'Drill Session'), ('other', 'Other')], default='practice', max_length=50)),
                ('external_booking_reference', models.CharField(blank=True, help_text='Booking confirmation number from external site (if any)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='e.g., "Doubles with Joe and Laura", "Working on serves"', null=True)),
                ('send_reminder', models.BooleanField(default=False, help_text='Send reminder notification before booking')),
                ('reminder_minutes_before', models.IntegerField(blank=True, help_text='Minutes before booking to send reminder (e.g., 60 for 1 hour)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court_location', models.ForeignKey(help_text='Which court location', on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to='courts.courtlocation')),
                ('user', models.ForeignKey(help_text='User who made this booking', on_delete=django.db.models.deletion.CASCADE, related_name='manual_court_bookings', to=settings.AUTH_USER_MODEL)),
                ('with_players', models.ManyToManyField(blank=True, help_text='Other users playing with you (if they have accounts)', related_name='shared_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Court Booking',
                'ordering': ['booking_date', 'start_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='courtclubaffiliation',
            unique_together={('court_location', 'club')},
        ),
    ]
