# Generated by Django 5.2.5 on 2025-12-07 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
        ('leagues', '0003_alter_roundrobinpattern_options_and_more'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtscheduleblock',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='courtscheduleblock',
            name='courts_affected',
        ),
        migrations.RemoveField(
            model_name='courtscheduleblock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='courtscheduleblock',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='courtscheduleblock',
            name='title',
        ),
        migrations.AddField(
            model_name='courtscheduleblock',
            name='cost_per_session',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per person per session (0.00 for free play)', max_digits=6),
        ),
        migrations.AddField(
            model_name='courtscheduleblock',
            name='max_players',
            field=models.IntegerField(blank=True, help_text='Maximum number of players allowed in this time block', null=True),
        ),
        migrations.AddField(
            model_name='courtscheduleblock',
            name='requires_reservation',
            field=models.BooleanField(default=False, help_text='Do users need to reserve a spot?'),
        ),
        migrations.AddField(
            model_name='courtscheduleblock',
            name='skill_level_max',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Maximum skill level allowed (e.g., 4.0 for up to 4.0)', max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='courtscheduleblock',
            name='skill_level_min',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Minimum skill level required (e.g., 3.5 for 3.5+ play)', max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='courtclubaffiliation',
            name='affiliation_type',
            field=models.IntegerField(choices=[(1, 'Priority Access'), (2, 'Exclusive Access (certain times)'), (3, 'Partner Club'), (4, 'Shared Access')], default=1),
        ),
        migrations.AlterField(
            model_name='courtclubaffiliation',
            name='notes',
            field=models.TextField(blank=True, help_text='e.g., "Club has priority Mondays 8-12pm" or "Exclusive access for leagues"'),
        ),
        migrations.AlterField(
            model_name='courtlocation',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Physical address of court location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_locations', to='public.address'),
        ),
        migrations.AlterField(
            model_name='courtlocation',
            name='booking_website',
            field=models.URLField(blank=True, help_text='Link to external booking site (e.g., www.pickleballenligne.com/PSJ)'),
        ),
        migrations.AlterField(
            model_name='courtlocation',
            name='description',
            field=models.TextField(blank=True, help_text='Additional info about the court (e.g., "Outdoor courts, covered")'),
        ),
        migrations.AlterField(
            model_name='courtlocation',
            name='photo',
            field=models.URLField(blank=True, help_text='Photo of court location'),
        ),
        migrations.AlterField(
            model_name='courtscheduleblock',
            name='block_type',
            field=models.IntegerField(blank=True, choices=[(1, 'League'), (2, 'Competitive Play'), (3, 'Recreative Play'), (4, 'Skill Restricted (3.5+, 4.0+, etc.)'), (5, 'Public Open Play'), (6, 'Drill/Training'), (7, 'Tournament'), (8, 'Blocked/Reserved'), (9, 'Maintenance/Closed')], null=True),
        ),
        migrations.AlterField(
            model_name='courtscheduleblock',
            name='league',
            field=models.ForeignKey(blank=True, help_text='Link to league if this is a league block', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='league_schedule_blocks', to='leagues.league'),
        ),
        migrations.AlterField(
            model_name='usercourtbooking',
            name='booking_type',
            field=models.IntegerField(choices=[(1, 'Practice Session'), (2, 'Casual Play'), (3, 'Lesson'), (4, 'Drill Session'), (5, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='usercourtbooking',
            name='court_number',
            field=models.CharField(blank=True, help_text='Specific court number (if known, e.g., "14", "Court 2", "T5")', max_length=20),
        ),
        migrations.AlterField(
            model_name='usercourtbooking',
            name='external_booking_reference',
            field=models.CharField(blank=True, help_text='Booking confirmation number from external site (if any)', max_length=100),
        ),
        migrations.AlterField(
            model_name='usercourtbooking',
            name='notes',
            field=models.TextField(blank=True, help_text='e.g., "Doubles with Joe and Laura", "Working on serves"'),
        ),
    ]
