# Generated by Django 5.2.5 on 2026-01-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_remove_courtscheduleblock_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtscheduleblock',
            name='background_color',
            field=models.CharField(blank=True, default='#bdc8d0', help_text='Color the block should show - default is Accent2'),
        ),
        migrations.AddField(
            model_name='courtscheduleblock',
            name='courts_used',
            field=models.IntegerField(default=1, help_text='Numbers of courts assigned for this block'),
        ),
        migrations.AddField(
            model_name='courtscheduleblock',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the block'),
        ),
        migrations.AddField(
            model_name='courtscheduleblock',
            name='text_color',
            field=models.CharField(blank=True, default='#1e2021', help_text='Color of the text shown on the block - default is on-Accent2'),
        ),
        migrations.AlterField(
            model_name='courtscheduleblock',
            name='block_type',
            field=models.IntegerField(blank=True, choices=[(1, 'League'), (2, 'Competitive Play'), (3, 'Recreative Play'), (4, 'Skill Restricted (3.5+, 4.0+, etc.)'), (5, 'Public Open Play'), (6, 'Drill/Training'), (7, 'Tournament'), (8, 'Blocked/Reserved'), (9, 'Maintenance/Closed')], default=5, null=True),
        ),
    ]
