# Generated by Django 5.2.5 on 2026-01-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_courtscheduleblock_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtscheduleblock',
            name='description',
        ),
        migrations.AddField(
            model_name='courtscheduleblock',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the block'),
        ),
    ]
