# Generated by Django 5.2.5 on 2026-02-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_remove_courtscheduleblock_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourtbooking',
            name='booking_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Booking Fee per session. NULL = free.', max_digits=6, null=True),
        ),
    ]
