# Generated by Django 5.2.5 on 2025-08-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='is_preferred_club',
            field=models.BooleanField(default=False),
        ),
    ]
