# Generated by Django 5.2.5 on 2025-11-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubmembership_is_preferred_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='requests',
            field=models.BooleanField(default=False),
        ),
    ]
