# Generated by Django 5.2.5 on 2025-11-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
