# Generated by Django 5.2.5 on 2025-11-29 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_short_name'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_location', to='public.address'),
        ),
    ]
