# Generated by Django 5.2.5 on 2025-11-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_club_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Cancelled'), (5, 'Blocked')], default=2, null=True),
        ),
    ]
