# Generated by Django 5.2.5 on 2025-12-01 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_clubmembership_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmembership',
            name='level',
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.clubmembershipskilllevel'),
        ),
    ]
