# Generated by Django 5.2.5 on 2025-12-07 12:39

import clubs.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_remove_clubmembership_level_clubmembership_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name'], 'verbose_name': 'Club', 'verbose_name_plural': 'Clubs'},
        ),
        migrations.AlterModelOptions(
            name='clubmembership',
            options={'ordering': ['-is_preferred_club', 'club__name'], 'verbose_name': 'Club Membership', 'verbose_name_plural': 'Club Memberships'},
        ),
        migrations.AlterModelOptions(
            name='clubmembershipskilllevel',
            options={'ordering': ['level'], 'verbose_name': 'Club Membership Skill Level', 'verbose_name_plural': 'Club Membership Skill Levels'},
        ),
        migrations.AlterModelOptions(
            name='clubmembershiptype',
            options={'verbose_name': 'Club Membership Type', 'verbose_name_plural': 'Club Membership Types'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RemoveField(
            model_name='club',
            name='requests',
        ),
        migrations.RemoveField(
            model_name='clubmembership',
            name='level',
        ),
        migrations.RemoveField(
            model_name='clubmembershiptype',
            name='type',
        ),
        migrations.AddField(
            model_name='club',
            name='autoapproval',
            field=models.BooleanField(default=False, help_text='If False, join requests require explicit admin approval. If True, users are auto-approved.'),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='club_memberships_at_level', to='clubs.clubmembershipskilllevel'),
        ),
        migrations.AddField(
            model_name='clubmembershipskilllevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubmembershipskilllevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clubmembershiptype',
            name='annual_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Annual membership fee (0.00 for free types like Junior)', max_digits=10),
        ),
        migrations.AddField(
            model_name='clubmembershiptype',
            name='club',
            field=models.ForeignKey(default=1, help_text='Club this membership type belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='membership_types', to='clubs.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubmembershiptype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubmembershiptype',
            name='max_capacity',
            field=models.IntegerField(blank=True, help_text='Maximum number of members for this type (null = unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='clubmembershiptype',
            name='max_capacity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max % of total club members (e.g., 30.00 for 30%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clubmembershiptype',
            name='name',
            field=models.CharField(default=1, help_text='Type name (e.g., Resident, Non-Resident, Junior)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubmembershiptype',
            name='registration_close_date',
            field=models.DateField(blank=True, help_text='When does registration close for this type?', null=True),
        ),
        migrations.AddField(
            model_name='clubmembershiptype',
            name='registration_open_date',
            field=models.DateField(blank=True, help_text='When does registration open for this type?', null=True),
        ),
        migrations.AddField(
            model_name='clubmembershiptype',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Does this type require admin approval?'),
        ),
        migrations.AddField(
            model_name='clubmembershiptype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='role',
            name='can_cancel_league_sessions',
            field=models.BooleanField(default=False, help_text='Can cancel/reinstate sessions only. Automatically true if can_manage_league_sessions=True.'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_create_training',
            field=models.BooleanField(default=False, help_text='Can create and manage training sessions'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_club',
            field=models.BooleanField(default=False, help_text='Full club administration privileges'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_courts',
            field=models.BooleanField(default=False, help_text='Can manage court bookings and availability'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_league_sessions',
            field=models.BooleanField(default=False, help_text='Can create/modify session details (location, day, time, courts). Implies can_cancel_league_sessions.'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_leagues',
            field=models.BooleanField(default=False, help_text='Can manage league members, create matches, view stats, edit league settings'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_members',
            field=models.BooleanField(default=False, help_text='Can add/remove/modify club members'),
        ),
        migrations.AddField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='short_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='registration_end_date',
            field=models.DateField(blank=True, default=clubs.models.get_default_end_date, null=True),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='registration_start_date',
            field=models.DateField(blank=True, default=clubs.models.get_default_start_date, null=True),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='club_memberships_with_role', to='clubs.role'),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Suspended'), (4, 'Cancelled'), (5, 'Blocked')], default=2),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='clubs.clubmembershiptype'),
        ),
        migrations.AlterField(
            model_name='clubmembershipskilllevel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clubmembershipskilllevel',
            name='level',
            field=models.IntegerField(choices=[(1, 'Open (Not Assessed)'), (2, '3.5+ (Advanced Intermediate)'), (3, '4.0+ (Advanced)')], help_text='Skill level designation', unique=True),
        ),
        migrations.AlterField(
            model_name='clubmembershiptype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Organizer'), (3, 'Captain'), (4, 'Instructor')], help_text='System role name', unique=True),
        ),
        migrations.AddIndex(
            model_name='clubmembership',
            index=models.Index(fields=['member', 'status'], name='clubs_clubm_member__2c1d62_idx'),
        ),
        migrations.AddIndex(
            model_name='clubmembership',
            index=models.Index(fields=['club', 'status'], name='clubs_clubm_club_id_549a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='clubmembership',
            index=models.Index(fields=['is_preferred_club'], name='clubs_clubm_is_pref_a83433_idx'),
        ),
    ]
