# Generated by Django 5.2.5 on 2025-12-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_alter_club_options_alter_clubmembership_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmembershiptype',
            options={'ordering': ['club', 'name'], 'verbose_name': 'Club Membership Type', 'verbose_name_plural': 'Club Membership Types'},
        ),
        migrations.AlterUniqueTogether(
            name='clubmembershiptype',
            unique_together={('club', 'name')},
        ),
    ]
