# Generated by Django 5.2.5 on 2025-12-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_alter_clubmembershiptype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Organizer'), (3, 'Captain'), (4, 'Instructor'), (5, 'Club Member')], help_text='System role name', unique=True),
        ),
    ]
