# Generated by Django 5.2.5 on 2026-01-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='banner_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='club_type',
            field=models.IntegerField(choices=[(1, 'Personal Club'), (2, 'Official Club')], default=2),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Suspended'), (4, 'Cancelled'), (5, 'Blocked'), (6, 'Expired')], default=2),
        ),
    ]
