# Generated by Django 5.2.5 on 2026-02-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_club_banner_url_club_club_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembershipskilllevel',
            name='max_level',
            field=models.DecimalField(decimal_places=1, default=6.0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='clubmembershipskilllevel',
            name='min_level',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='membership_number',
            field=models.CharField(blank=True, default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
