# Generated by Django 5.2.5 on 2026-02-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_clubmembershipskilllevel_max_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembershipskilllevel',
            name='short_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='clubmembershipskilllevel',
            name='level',
            field=models.IntegerField(choices=[(1, 'Open (Not Assessed)'), (2, '3.5+ (Advanced Intermediate)'), (3, '4.0+ (Advanced)'), (4, '2.8-3.1 (Light Intermediate)'), (5, '3.2-3.4 (Intermediate)'), (6, '2.0-2.7 (Beginner)')], help_text='Skill level designation', unique=True),
        ),
    ]
