# Generated by Django 5.2.5 on 2026-02-27 16:10

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_clubmembershipskilllevel_short_name_and_more'),
    ]

    operations = [

        # FIRST: Remove unique=True from name field
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.IntegerField(
                choices=[(1, 'Admin'), (2, 'Organizer'), (3, 'Captain'), (4, 'Instructor'), (5, 'Club Member')],
                help_text='System role name'
            ),
        ),
        # Add club FK (nullable initially - we'll populate it, then make it required)
        migrations.AddField(
            model_name='role',
            name='club',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='roles',
                to='clubs.club',
                help_text='Club this role belongs to'
            ),
        ),
    ]
