# Generated by Django 5.2.5 on 2026-02-27 16:15

from django.db import migrations


def create_club_specific_roles(apps, schema_editor):
    """
    For each existing club, create 5 club-specific role instances.
    
    Default permissions differ based on club type:
    - Personal clubs: Collaborative (members can manage events)
    - Official clubs: Strict (only admins/organizers can manage events)
    """
    Club = apps.get_model('clubs', 'Club')
    Role = apps.get_model('clubs', 'Role')
    
    # Import constants - NOTE: Can't import from public.constants in migrations!
    # We'll use hardcoded integer values
    PERSONAL = 1  # ClubType.PERSONAL
    OFFICIAL = 2  # ClubType.OFFICIAL
    
    ADMIN = 1       # RoleType.ADMIN
    ORGANIZER = 2   # RoleType.ORGANIZER
    CAPTAIN = 3     # RoleType.CAPTAIN
    INSTRUCTOR = 4  # RoleType.INSTRUCTOR
    MEMBER = 5      # RoleType.MEMBER
    
    # Get current global roles (for reference - to copy descriptions)
    global_admin = Role.objects.filter(club__isnull=True, name=ADMIN).first()
    global_organizer = Role.objects.filter(club__isnull=True, name=ORGANIZER).first()
    global_captain = Role.objects.filter(club__isnull=True, name=CAPTAIN).first()
    global_instructor = Role.objects.filter(club__isnull=True, name=INSTRUCTOR).first()
    global_member = Role.objects.filter(club__isnull=True, name=MEMBER).first()
    
    for club in Club.objects.all():
        is_personal = club.club_type == PERSONAL
        
        # Create ADMIN role (same for all clubs - god mode!)
        Role.objects.create(
            club=club,
            name=ADMIN,
            description=global_admin.description if global_admin else 'Full club administration',
            can_manage_club=True,
            can_manage_members=True,
            can_create_training=True,
            can_manage_leagues=True,
            can_manage_league_sessions=True,
            can_cancel_league_sessions=True,
            can_manage_courts=True,
        )
        
        # Create ORGANIZER role
        Role.objects.create(
            club=club,
            name=ORGANIZER,
            description=global_organizer.description if global_organizer else 'Event and league organizer',
            can_manage_club=False,
            can_manage_members=True if is_personal else False,  # Personal: collaborative
            can_create_training=True,
            can_manage_leagues=True,
            can_manage_league_sessions=True,
            can_cancel_league_sessions=True,
            can_manage_courts=True,
        )
        
        # Create CAPTAIN role
        Role.objects.create(
            club=club,
            name=CAPTAIN,
            description=global_captain.description if global_captain else 'League captain',
            can_manage_club=False,
            can_manage_members=False,
            can_create_training=False,
            can_manage_leagues=True,
            can_manage_league_sessions=False,
            can_cancel_league_sessions=True,
            can_manage_courts=False,
        )
        
        # Create INSTRUCTOR role
        Role.objects.create(
            club=club,
            name=INSTRUCTOR,
            description=global_instructor.description if global_instructor else 'Training instructor',
            can_manage_club=False,
            can_manage_members=False,
            can_create_training=True,
            can_manage_leagues=False,
            can_manage_league_sessions=False,
            can_cancel_league_sessions=False,
            can_manage_courts=False,
        )
        
        # Create MEMBER role (DIFFERENT for personal vs official!)
        Role.objects.create(
            club=club,
            name=MEMBER,
            description=global_member.description if global_member else 'Club member',
            can_manage_club=False,
            can_manage_members=False,
            can_create_training=False,
            can_manage_leagues=False,
            can_manage_league_sessions=False,
            can_cancel_league_sessions=False,
            can_manage_courts=False,
        )
class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_add_club_to_role'),
    ]

    operations = [
        migrations.RunPython(create_club_specific_roles),
    ]
