# Generated by Django 5.2.5 on 2026-02-27 16:34

from django.db import migrations

def update_membership_roles(apps, schema_editor):
    """
    Update existing ClubMembership.roles to point to club-specific Role instances.
    
    For each membership:
    1. Get current global roles (club=NULL)
    2. Replace with equivalent club-specific roles
    """
    ClubMembership = apps.get_model('clubs', 'ClubMembership')
    Role = apps.get_model('clubs', 'Role')
    
    for membership in ClubMembership.objects.all():
        club = membership.club
        current_roles = list(membership.roles.filter(club__isnull=True))  # Get global roles
        
        # Clear current roles
        membership.roles.clear()
        
        # Add equivalent club-specific roles
        for old_role in current_roles:
            try:
                new_role = Role.objects.get(club=club, name=old_role.name)
                membership.roles.add(new_role)
            except Role.DoesNotExist:
                # Should never happen if migration 2 worked correctly
                print(f"WARNING: No club-specific role found for {club.name} - {old_role.name}")
                pass
class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_create_club_specific_roles'),
    ]

    operations = [
        migrations.RunPython(update_membership_roles),
    ]
