# Generated by Django 5.2.5 on 2026-02-27 17:38

from django.db import migrations

def delete_global_roles(apps, schema_editor):
    """Delete old global roles (club=NULL)"""
    Role = apps.get_model('clubs', 'Role')
    deleted_count = Role.objects.filter(club__isnull=True).delete()[0]
    print(f"✅ Deleted {deleted_count} global roles")

class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_update_membership_roles'),
    ]

    operations = [
        migrations.RunPython(delete_global_roles),
    ]
