# Generated by Django 5.2.5 on 2026-02-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_delete_global_roles'),
    ]

    operations = [
        # Make club FK required
        migrations.AlterField(
            model_name='role',
            name='club',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name='roles',
                to='clubs.club',
                help_text='Club this role belongs to'
            ),
        ),
        
        # Update unique constraint
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('club', 'name')},
        ),
    ]
