# Generated by Django 5.2.5 on 2026-02-28 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_make_club_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['club', 'name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterField(
            model_name='role',
            name='club',
            field=models.ForeignKey(help_text='Club this role belongs to. Null = global system role.', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='clubs.club'),
        ),
    ]
