# Generated by Django 5.2.5 on 2025-12-01 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0007_remove_clubmembership_level_clubmembership_level'),
        ('courts', '0001_initial'),
        ('leagues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(help_text='REQUIRED! MLP league this team plays in', on_delete=django.db.models.deletion.CASCADE, related_name='mlp_teams', to='leagues.league')),
            ],
            options={
                'verbose_name': 'MLP Team',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('match_format', models.CharField(choices=[('best_of_1', 'Best of 1 (Single Game)'), ('best_of_3', 'Best of 3'), ('best_of_5', 'Best of 5')], max_length=20)),
                ('match_type', models.CharField(choices=[('singles', 'Singles'), ('doubles', 'Doubles'), ('mlp', 'MLP Team Match')], max_length=20)),
                ('score_format', models.CharField(choices=[('sideout', 'Side-out Scoring'), ('rally', 'Rally Scoring')], max_length=20)),
                ('match_status', models.CharField(choices=[('pending', 'Pending - Players invited'), ('accepted', 'Accepted - All players confirmed'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed - Results entered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Why was this match cancelled? (e.g., rain, insufficient players, abandoned mid-match)', null=True)),
                ('court_number', models.CharField(blank=True, help_text='Specific court number (e.g., "1", "Court 2", "14")', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, help_text='Club if club tournament', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='clubs.club')),
                ('court_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='courts.courtlocation')),
                ('league', models.ForeignKey(blank=True, help_text='League if league match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='leagues.league')),
                ('organized_by', models.ForeignKey(blank=True, help_text='User who organized this match (for private matches)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_matches', to=settings.AUTH_USER_MODEL)),
                ('result_entered_by', models.ForeignKey(blank=True, help_text='User who entered the result (for audit trail)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_entered', to=settings.AUTH_USER_MODEL)),
                ('user_booking', models.OneToOneField(blank=True, help_text='Link to manual booking if this is a private match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match', to='courts.usercourtbooking')),
                ('winning_mlp_team', models.ForeignKey(blank=True, help_text='MLP team that won (for MLP matches only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='matches.mlpteam')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlp_game_type', models.CharField(blank=True, choices=[('women_doubles', "Women's Doubles"), ('men_doubles', "Men's Doubles"), ('mixed_doubles_1', 'Mixed Doubles 1'), ('mixed_doubles_2', 'Mixed Doubles 2'), ('dreambreaker', 'DreamBreaker')], help_text='Type of MLP game. Match to Game.mlp_game_type to find teams.', max_length=20, null=True)),
                ('team_name', models.CharField(blank=True, help_text='e.g., "Team A", "Joe & Tina", "Thunderstruck"', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='matches.match')),
                ('mlp_team', models.ForeignKey(blank=True, help_text='MLP team entity (if this is an MLP match)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_teams', to='matches.mlpteam')),
            ],
            options={
                'ordering': ['match', 'id'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='winning_team',
            field=models.ForeignKey(blank=True, help_text='Team that won (for singles/doubles matches)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='matches.team'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField()),
                ('team1_score', models.IntegerField()),
                ('team2_score', models.IntegerField()),
                ('mlp_game_type', models.CharField(blank=True, choices=[('women_doubles', "Women's Doubles"), ('men_doubles', "Men's Doubles"), ('mixed_doubles_1', 'Mixed Doubles 1'), ('mixed_doubles_2', 'Mixed Doubles 2'), ('dreambreaker', 'DreamBreaker')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='matches.match')),
                ('game_loser_team', models.ForeignKey(help_text='REQUIRED! Simplifies queries for stats.', on_delete=django.db.models.deletion.PROTECT, related_name='games_lost', to='matches.team')),
                ('game_winner_team', models.ForeignKey(help_text='REQUIRED! Game only exists if completed.', on_delete=django.db.models.deletion.PROTECT, related_name='games_won', to='matches.team')),
            ],
            options={
                'ordering': ['match', 'game_number'],
            },
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_participations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='matches.team')),
            ],
            options={
                'ordering': ['team', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='mlpteam',
            constraint=models.UniqueConstraint(fields=('league', 'name'), name='unique_mlp_team_per_league'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('mlp_team__isnull', False)), fields=('match', 'mlp_team', 'mlp_game_type'), name='unique_mlp_team_per_game_type'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('game_winner_team', models.F('game_loser_team')), _negated=True), name='winner_not_equal_loser', violation_error_message='Winner and loser cannot be same team!'),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('match', 'game_number')},
        ),
        migrations.AlterUniqueTogether(
            name='teamplayer',
            unique_together={('team', 'player')},
        ),
    ]
