# Generated by Django 5.2.5 on 2025-12-07 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_remove_courtscheduleblock_background_color_and_more'),
        ('leagues', '0003_alter_roundrobinpattern_options_and_more'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='generation_format',
            field=models.IntegerField(blank=True, choices=[(1, 'Round-Robin'), (2, 'King of the Court'), (3, 'Manual Entry')], help_text='How matches were generated: Round-Robin, King-of-Court, or Manual. Set by captain when generating matches.', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_matches', to='leagues.leaguesession'),
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.IntegerField(blank=True, help_text='Round number (1-16) for round-robin format only. NULL for other formats.', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='mlp_game_type',
            field=models.IntegerField(blank=True, choices=[(1, "Women's Doubles"), (2, "Men's Doubles"), (3, 'Mixed Doubles 1'), (4, 'Mixed Doubles 2'), (5, 'DreamBreaker')], null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Why was this match cancelled? (e.g., rain, insufficient players, abandoned mid-match)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='court_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_played', to='courts.courtlocation'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_format',
            field=models.IntegerField(choices=[(1, 'Best of 1 (Single Game)'), (2, 'Best of 3'), (3, 'Best of 5')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.IntegerField(choices=[(1, 'Pending - Players invited'), (2, 'Accepted - All players confirmed'), (3, 'Scheduled'), (4, 'In Progress'), (5, 'Completed - Results entered'), (6, 'Cancelled')], default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.IntegerField(choices=[(1, 'Singles'), (2, 'Doubles'), (3, 'MLP Team Match')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_format',
            field=models.IntegerField(choices=[(1, 'Side-out Scoring'), (2, 'Rally Scoring')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='winning_mlp_team',
            field=models.ForeignKey(blank=True, help_text='MLP team that won (for MLP matches only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlp_team_matches_won', to='matches.mlpteam'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winning_team',
            field=models.ForeignKey(blank=True, help_text='Team that won (for singles/doubles matches)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_matches_won', to='matches.team'),
        ),
        migrations.AlterField(
            model_name='mlpteam',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='mlp_game_type',
            field=models.IntegerField(blank=True, choices=[(1, "Women's Doubles"), (2, "Men's Doubles"), (3, 'Mixed Doubles 1'), (4, 'Mixed Doubles 2'), (5, 'DreamBreaker')], help_text='Type of MLP game. Match to Game.mlp_game_type to find teams.', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(blank=True, help_text='e.g., "Team A", "Joe & Tina", "Thunderstruck"', max_length=100),
        ),
        migrations.CreateModel(
            name='MLPTeamRosterPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.CharField(blank=True, help_text='Optional jersey number for this player', max_length=10, null=True)),
                ('position_notes', models.CharField(blank=True, help_text='Optional position notes (e.g., "Primary for women\'s doubles")', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(help_text='Player in this roster', on_delete=django.db.models.deletion.CASCADE, related_name='mlp_roster_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MLP Team Roster Player',
                'ordering': ['roster_version', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MLPTeamRosterVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(help_text='Auto-incremented version (1, 2, 3, ...)')),
                ('effective_from', models.DateField(help_text='Date this roster version became active')),
                ('is_active', models.BooleanField(default=True, help_text='Is this the current active roster?')),
                ('change_notes', models.TextField(blank=True, help_text='Optional notes about roster change (e.g., "Added John after Mike injured")')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='Admin/captain who made this roster change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlp_roster_changes_made', to=settings.AUTH_USER_MODEL)),
                ('mlp_team', models.ForeignKey(help_text='Which MLP team this roster belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='roster_versions', to='matches.mlpteam')),
                ('players', models.ManyToManyField(help_text='Players in this roster version', related_name='mlp_roster_versions', through='matches.MLPTeamRosterPlayer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MLP Team Roster Version',
                'ordering': ['mlp_team', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='mlpteamrosterplayer',
            name='roster_version',
            field=models.ForeignKey(help_text='Which roster version this player belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='roster_players', to='matches.mlpteamrosterversion'),
        ),
        migrations.AddConstraint(
            model_name='mlpteamrosterversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('mlp_team',), name='one_active_roster_per_team'),
        ),
        migrations.AlterUniqueTogether(
            name='mlpteamrosterversion',
            unique_together={('mlp_team', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='mlpteamrosterplayer',
            unique_together={('roster_version', 'player')},
        ),
    ]
