# Generated by Django 5.2.5 on 2025-08-28 15:45

import django.db.models.deletion
import leagues.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('public', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('max_courts', models.IntegerField(default=1)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_location', to='public.address')),
            ],
        ),
        migrations.CreateModel(
            name='CourtLocationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.CharField(help_text="e.g., 'Courts blocked for Tennis club'.", max_length=200)),
                ('court_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='leagues.courtlocation')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(default=leagues.models.get_default_start_date)),
                ('end_date', models.DateField(default=leagues.models.get_default_end_date)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='clubs.club')),
                ('level', models.ManyToManyField(related_name='leagues_with_level', to='clubs.clubmembershipskilllevel')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_number', models.IntegerField(null=True, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_participations_as_club_member', to='clubs.clubmembership')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_participations', to='leagues.league')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_participations', to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(related_name='league_participations_with_role', to='clubs.role')),
            ],
            options={
                'unique_together': {('club_membership', 'league')},
            },
        ),
        migrations.AddField(
            model_name='league',
            name='participants',
            field=models.ManyToManyField(related_name='leagues_as_participant', through='leagues.LeagueParticipation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LeagueSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courts_used', models.IntegerField(help_text='The number of courts used for this session.')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('recurrence_type', models.CharField(choices=[('weekly', 'Weekly'), ('bi_weekly', 'Every other week'), ('monthly', 'Once a month')], max_length=20)),
                ('recurrence_interval', models.IntegerField(default=1, help_text="e.g., 2 for 'Every other week' or 1 for 'Once a month' on the first week.")),
                ('court_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='leagues.courtlocation')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='leagues.league')),
            ],
        ),
    ]
