# Generated by Django 5.2.5 on 2025-12-01 17:09

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_remove_clubmembership_level_clubmembership_level'),
        ('courts', '0001_initial'),
        ('leagues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtlocation',
            name='address',
        ),
        migrations.AlterField(
            model_name='leaguesession',
            name='court_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_sessions', to='courts.courtlocation'),
        ),
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['-start_date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='leagueparticipation',
            options={'ordering': ['league', 'member']},
        ),
        migrations.AlterModelOptions(
            name='leaguesession',
            options={'ordering': ['league', 'day_of_week', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='league',
            name='level',
        ),
        migrations.RemoveField(
            model_name='leagueparticipation',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='leagueparticipation',
            name='participant_number',
        ),
        migrations.RemoveField(
            model_name='leagueparticipation',
            name='roles',
        ),
        migrations.AddField(
            model_name='league',
            name='allow_reserves',
            field=models.BooleanField(default=True, help_text='❗️ If True, users can join as reserves when league is full'),
        ),
        migrations.AddField(
            model_name='league',
            name='captain',
            field=models.ForeignKey(help_text='League captain who manages this league', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues_as_captain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='league',
            name='default_match_format',
            field=models.CharField(blank=True, choices=[('round_robin', 'Round-Robin'), ('king_of_court', 'King of the Court'), ('manual', 'Manual Entry')], default='round_robin', help_text='Default format for match generation. Only applies to Standard leagues. Captain can override per session.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='league',
            name='league_type',
            field=models.CharField(choices=[('standard', 'Standard (Rotating Partners)'), ('team', 'Team-Based (Fixed 2-Player Teams)'), ('mlp', 'MLP (Fixed 4+ Player Teams)')], default='standard', help_text='Standard=rotating partners, Team=fixed pairs, MLP=fixed 4+ teams', max_length=20),
        ),
        migrations.AddField(
            model_name='league',
            name='max_participants',
            field=models.IntegerField(blank=True, help_text='Maximum number of ACTIVE participants (leave blank for unlimited). ❗️ Additional joiners become RESERVE.', null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='minimum_skill_level',
            field=models.ForeignKey(blank=True, help_text='Minimum skill level required (e.g., 3.5+ means 3.5, 4.0, 4.5, 5.0 allowed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues_with_min_skill', to='clubs.clubmembershipskilllevel'),
        ),
        migrations.AddField(
            model_name='league',
            name='registration_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leagueparticipation',
            name='captain_notes',
            field=models.TextField(blank=True, help_text='Private notes from captain (e.g., "Struggles with serve", "Strong backhand")', null=True),
        ),
        migrations.AddField(
            model_name='leagueparticipation',
            name='exclude_from_rankings',
            field=models.BooleanField(default=False, help_text='Exclude this player from league statistics and rankings (e.g., captain who coaches/substitutes)'),
        ),
        migrations.AddField(
            model_name='leagueparticipation',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leagueparticipation',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leagueparticipation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('reserve', 'Reserve - Waiting for spot'), ('injured', 'Injured - Temporarily out'), ('holiday', 'On Holiday - Temporarily out'), ('dropped', 'Dropped Out')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='leaguesession',
            name='active_from',
            field=models.DateField(blank=True, help_text='When session schedule starts (default: league start_date)', null=True),
        ),
        migrations.AddField(
            model_name='leaguesession',
            name='active_until',
            field=models.DateField(blank=True, help_text='When session schedule ends (default: league end_date)', null=True),
        ),
        migrations.AddField(
            model_name='leaguesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 1, 17, 9, 4, 246105, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaguesession',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='League organizer who created this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='league_sessions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaguesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leaguesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='LeagueAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='Specific date of this session')),
                ('status', models.CharField(choices=[('attending', 'Attending'), ('cancelled', 'Cancelled'), ('absent', 'Absent (no-show)')], default='attending', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Optional reason for cancellation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league_participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='leagues.leagueparticipation')),
            ],
            options={
                'ordering': ['session_date', 'league_participation'],
                'unique_together': {('league_participation', 'session_date')},
            },
        ),
        migrations.CreateModel(
            name='RoundRobinPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_courts', models.IntegerField(help_text='Number of courts for this pattern')),
                ('num_players', models.IntegerField(help_text='Number of players for this pattern')),
                ('name', models.CharField(help_text='e.g., "5 Courts - 22 Players Standard"', max_length=100)),
                ('pattern_data', models.JSONField(help_text='JSON structure of rotation pattern')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['num_courts', 'num_players'],
                'unique_together': {('num_courts', 'num_players')},
            },
        ),
        migrations.DeleteModel(
            name='CourtLocationSchedule',
        ),
        migrations.DeleteModel(
            name='CourtLocation',
        ),
    ]
