# Generated by Django 5.2.5 on 2025-12-07 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_remove_courtlocation_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roundrobinpattern',
            options={'ordering': ['num_players']},
        ),
        migrations.AlterUniqueTogether(
            name='leagueattendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='roundrobinpattern',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='league',
            name='default_match_format',
        ),
        migrations.AddField(
            model_name='league',
            name='default_generation_format',
            field=models.IntegerField(blank=True, choices=[(1, 'Round-Robin'), (2, 'King of the Court'), (3, 'Manual Entry')], default=1, help_text='Default format for match generation. Only applies to Standard leagues. Captain can override per session.', null=True),
        ),
        migrations.AddField(
            model_name='leagueattendance',
            name='arrived_before_round',
            field=models.IntegerField(blank=True, help_text='Which round player arrived before (e.g., 4). NULL = was not late.', null=True),
        ),
        migrations.AddField(
            model_name='leagueattendance',
            name='checked_in',
            field=models.BooleanField(default=False, help_text='Did the player check in / show up on the day? (captain confirms)'),
        ),
        migrations.AddField(
            model_name='leagueattendance',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, help_text='Captain/co-captain who performed day-of check-in (useful for multi-captain leagues)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leagueattendance',
            name='league_session',
            field=models.ForeignKey(default=1, help_text='Which recurring session schedule this attendance is for', on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to='leagues.leaguesession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leagueattendance',
            name='left_after_round',
            field=models.IntegerField(blank=True, help_text='Which round player left after (e.g., 3). NULL = did not leave early.', null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='league_type',
            field=models.IntegerField(choices=[(1, 'Standard (Rotating Partners)'), (2, 'Team-Based (Fixed 2-Player Teams)'), (3, 'MLP (Fixed 4+ Player Teams)')], default=1, help_text='Standard=rotating partners, Team=fixed pairs, MLP=fixed 4+ teams'),
        ),
        migrations.AlterField(
            model_name='leagueattendance',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Optional reason for cancellation'),
        ),
        migrations.AlterField(
            model_name='leagueattendance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Attending'), (2, 'Cancelled'), (3, 'Absent (no-show)')], default=1),
        ),
        migrations.AlterField(
            model_name='leagueparticipation',
            name='captain_notes',
            field=models.TextField(blank=True, help_text='Private notes from captain (e.g., "Struggles with serve", "Strong backhand")'),
        ),
        migrations.AlterField(
            model_name='leagueparticipation',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_participants', to='leagues.league'),
        ),
        migrations.AlterField(
            model_name='leagueparticipation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Reserve - Waiting for spot'), (3, 'Injured - Temporarily out'), (4, 'On Holiday - Temporarily out'), (5, 'Dropped Out')], default=1),
        ),
        migrations.AlterField(
            model_name='leaguesession',
            name='courts_used',
            field=models.IntegerField(default=1, help_text='The number of courts used for this session.'),
        ),
        migrations.AlterField(
            model_name='leaguesession',
            name='recurrence_type',
            field=models.IntegerField(choices=[(1, 'Weekly'), (2, 'Every other week'), (3, 'Once a month')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='leagueattendance',
            unique_together={('league_participation', 'league_session', 'session_date')},
        ),
        migrations.RemoveField(
            model_name='roundrobinpattern',
            name='num_courts',
        ),
        migrations.CreateModel(
            name='SessionCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_from', models.DateField(help_text='First date of cancellation (inclusive)')),
                ('cancelled_until', models.DateField(help_text='Last date of cancellation (inclusive)')),
                ('reason', models.CharField(blank=True, help_text='Why captain cancelled (personal, weather, venue closed, etc.)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Captain who created this cancellation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_cancellations_made', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='Which recurring session to cancel', on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='leagues.leaguesession')),
            ],
            options={
                'ordering': ['-cancelled_from'],
                'indexes': [models.Index(fields=['session', 'cancelled_from', 'cancelled_until'], name='leagues_ses_session_39c714_idx')],
            },
        ),
    ]
