# Generated by Django 5.2.5 on 2026-01-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_alter_roundrobinpattern_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='allow_waitlist',
            field=models.BooleanField(default=True, help_text='Allow users to join waitlist when session full'),
        ),
        migrations.AddField(
            model_name='league',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='league',
            name='is_event',
            field=models.BooleanField(default=False, help_text='True = Event (per-session), False = League (season enrollment)'),
        ),
        migrations.AddField(
            model_name='league',
            name='max_spots_per_session',
            field=models.PositiveIntegerField(blank=True, help_text='Max registrations per session (for events only)', null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='registration_closes_hours_before',
            field=models.PositiveIntegerField(default=2, help_text='How many hours before session registration closes'),
        ),
        migrations.AddField(
            model_name='league',
            name='registration_opens_hours_before',
            field=models.PositiveIntegerField(default=168, help_text='How many hours before session registration opens'),
        ),
    ]
