# Generated by Django 5.2.5 on 2026-01-12 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_league_allow_waitlist_league_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leagueattendance',
            options={'ordering': ['session_occurrence', 'league_participation']},
        ),
        migrations.AlterModelOptions(
            name='roundrobinpattern',
            options={'ordering': ['num_players'], 'verbose_name': 'Round-Robin Pattern', 'verbose_name_plural': 'Round-Robin Patterns'},
        ),
        migrations.RemoveField(
            model_name='league',
            name='allow_waitlist',
        ),
        migrations.RemoveField(
            model_name='league',
            name='max_spots_per_session',
        ),
        migrations.RemoveField(
            model_name='league',
            name='registration_open',
        ),
        migrations.AddField(
            model_name='league',
            name='registration_end_date',
            field=models.DateField(blank=True, help_text='[LEAGUES] When registration closes (NULL = stays open)', null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='registration_start_date',
            field=models.DateField(blank=True, help_text='[LEAGUES] When registration opens (NULL = open immediately)', null=True),
        ),
        migrations.AddField(
            model_name='roundrobinpattern',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='allow_reserves',
            field=models.BooleanField(default=True, help_text='Allow overflow participants when full. For LEAGUES: Season-long RESERVE list. For EVENTS: Per-session WAITLIST.'),
        ),
        migrations.AlterField(
            model_name='league',
            name='max_participants',
            field=models.IntegerField(blank=True, help_text='Maximum number of participants (unlimited if blank). For LEAGUES: Season enrollment cap (additional joiners become reserves). For EVENTS: Per-session cap (additional joiners join waitlist).', null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='registration_closes_hours_before',
            field=models.PositiveIntegerField(default=2, help_text='[EVENTS] Hours before session start that registration closes'),
        ),
        migrations.AlterField(
            model_name='league',
            name='registration_opens_hours_before',
            field=models.PositiveIntegerField(default=168, help_text='[EVENTS] Hours before session start that registration opens'),
        ),
        migrations.AlterField(
            model_name='roundrobinpattern',
            name='num_players',
            field=models.IntegerField(help_text='Number of players for this pattern', unique=True),
        ),
        migrations.CreateModel(
            name='SessionOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='Specific date of this session')),
                ('start_datetime', models.DateTimeField(help_text='Exact start (date + time combined)')),
                ('end_datetime', models.DateTimeField(help_text='Exact end (date + time combined)')),
                ('registration_opens_at', models.DateTimeField(blank=True, help_text='When registration opens for this session (events only)', null=True)),
                ('registration_closes_at', models.DateTimeField(blank=True, help_text='When registration closes for this session (events only)', null=True)),
                ('is_cancelled', models.BooleanField(default=False, help_text='Captain cancelled this specific occurrence')),
                ('cancellation_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='leagues.leaguesession')),
            ],
            options={
                'ordering': ['session_date', 'league_session'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='leagueattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leagueattendance',
            name='session_occurrence',
            field=models.ForeignKey(default=1, help_text='Which specific session occurrence this attendance is for', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='leagues.sessionoccurrence'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='leagueattendance',
            unique_together={('league_participation', 'session_occurrence')},
        ),
        migrations.AddIndex(
            model_name='sessionoccurrence',
            index=models.Index(fields=['session_date', 'league_session'], name='leagues_ses_session_57fc53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionoccurrence',
            unique_together={('league_session', 'session_date')},
        ),
        migrations.RemoveField(
            model_name='leagueattendance',
            name='league_session',
        ),
        migrations.RemoveField(
            model_name='leagueattendance',
            name='session_date',
        ),
    ]
