# Generated by Django 5.2.5 on 2026-01-18 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_alter_leagueattendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee per session (events) or season enrollment (leagues). NULL = free.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='sessionoccurrence',
            name='league',
            field=models.ForeignKey(default=1, help_text='Direct link to league (denormalized for performance)', on_delete=django.db.models.deletion.CASCADE, related_name='all_occurrences', to='leagues.league'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaguesession',
            name='recurrence_type',
            field=models.IntegerField(choices=[(0, 'One-time'), (1, 'Weekly'), (2, 'Every other week'), (3, 'Once a month')], default=1),
        ),
        migrations.AddIndex(
            model_name='sessionoccurrence',
            index=models.Index(fields=['league', 'session_date', 'is_cancelled'], name='leagues_ses_league__f988f7_idx'),
        ),
    ]
