# Generated by Django 5.2.5 on 2026-02-28 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_alter_role_options_alter_role_club'),
        ('leagues', '0006_league_fee_sessionoccurrence_league_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='minimum_skill_level',
            field=models.ForeignKey(blank=True, help_text='Required skill Level (e.g., 3.5+ means only 3.5+ players can join. 4.0+ or Inter 1 can not join).)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues_with_min_skill', to='clubs.clubmembershipskilllevel'),
        ),
        migrations.AlterField(
            model_name='leagueattendance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Attending'), (2, 'Cancelled'), (3, 'Absent (no-show)'), (4, 'Waitlisted')], default=1),
        ),
        migrations.AlterField(
            model_name='leagueparticipation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Reserve - Waiting for spot'), (3, 'Injured - Temporarily out'), (4, 'On Holiday - Temporarily out'), (5, 'Dropped Out'), (6, 'Pending')], default=1),
        ),
        migrations.AlterField(
            model_name='leaguesession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaguesession',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
