# Generated by Django 5.2.5 on 2026-01-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_bio_alter_customuser_home_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='created_at',
            new_name='joined_date',
        ),
    ]
