# Generated by Django 5.2.5 on 2026-01-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_created_at_customuser_joined_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='joined_date',
            new_name='created_at',
        ),
    ]
